site_title: Dinanath Thakur
name: Dinanath Thakur
description: Software Engineer | Backend Developer
email_id: kumardina023@gmail.com
mobile_number: +91-8236064628
contact_details: kumardina023@gmail.com | +91-8236064628
show_downloads: false
theme: jekyll-theme-hacker
stack_overflow_profile_url: https://stackoverflow.com/users/5269827/dinanath-thakur
linkedin_profile_url: https://www.linkedin.com/in/dinanaththakur/